### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xn0px90**
added Vinix

### CODE REVIEW

**Comment by SuperErnD** [comment]
its broken

**Comment by xn0px90** [comment]
working on it!

**Comment by xn0px90** [comment]
Mintsuki thank you for your commits and helping us with vinix and getting and iso to continue working!
We appreciate it greatly!!!
thank you again!!!
~X

**Review by SuperErnD — COMMENTED** [review]
I mean README.md is broken, before [Lyre] should be comma, not after

**Pull request closed without merging**
